name: ci

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  pre-commit:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: run pre-commit-action
        uses: pre-commit/action@v2.0.0
        
